name = "Rookie Club"
license = "CC0"
licenselink = "https://github.com/rookie-club/rookie-club/blob/master/LICENSE.md"
description = ""
homepage = "http://rookie-club.ut7.fr/"
tags = []
features = []
min_version = "0.30.2"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
